esphome:
  name: sofar-solar-esp
  comment: SofarSolar Logger (Modbus/RS485)

esp32:
  board: esp32dev
  framework:
    type: arduino

substitutions:
  devicename: sofar-monitor
  friendly_name: SofarSolar
  hostname: "esp32-sofar"
  comment: "SofarSolar modbus interface"
  icon: "mdi:solar-power-variant-outline"
  restore_mode: "restore_default_off"

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:

wifi:
  ssid: ""
  password: ""
  reboot_timeout: 120s
  ap:
    ssid: "Esphome-Web-4Be4Cc"
    password: ""
    ap_timeout: 300s


captive_portal: 
logger:
  level: INFO


uart:
  id: mod_bus
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600
  stop_bits: 1
  debug:
modbus:
  id: mod_bus_sofar
 
modbus_controller:
  - id: sofarsolar
    address: 0x01
    modbus_id: mod_bus_sofar
    update_interval: 5s
    command_throttle: 20ms
 
text_sensor:
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Status
    id: inverter_status
    register_type: holding
    address: 0x0404
    response_size: 2
    lambda: |-
      auto z = "Unknown";
      char d = data[item->offset+1];
      if (d == 0) z = "Wait";
      else if (d == 1) z = "Check";
      else if (d == 2) z = "Normal";
      else if (d == 3) z = "EPS";
      else if (d == 4) z = "Fault";
      else if (d == 5) z = "Permanent";
      else if (d == 6) z = "Upgrade";
      else if (d == 2) z = "Self charging";
      return {z};
    skip_updates: 10
 
sensor:
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_1
    address: 0x0405
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_2
    address: 0x0406
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_3
    address: 0x0407
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_4
    address: 0x0408
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_5
    address: 0x0409
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_6
    address: 0x040A
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_7
    address: 0x040B
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_8
    address: 0x040C
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_9
    address: 0x040D
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_10
    address: 0x040E
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_11
    address: 0x040F
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_12
    address: 0x0410
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_13
    address: 0x0411
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_14
    address: 0x0412
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_15
    address: 0x0413
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_16
    address: 0x0414
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_17
    address: 0x0415
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: fault_18
    address: 0x0416
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    
 
  - platform: wifi_signal
    id: inverter_wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s
  - platform: uptime
    id: inverter_uptime
    name: ${friendly_name} Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} 0x0400
    address: 0x0400
    register_type: holding
    value_type: U_QWORD
    unit_of_measurement: ' '
    internal: true
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Countdown
    address: 0x0417
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: ' '
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp Env 1
    address: 0x0418
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    filters:
      - filter_out: 0
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp Env 2
    address: 0x0419
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp HS 1
    address: 0x041A
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    filters:
      - filter_out: 0
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp HS 2
    address: 0x041B
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp HS 3
    address: 0x041C
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp HS 4
    address: 0x041D
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp HS 5
    address: 0x041E
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp HS 6
    address: 0x041F
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp Inverter 1
    address: 0x0420
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp Inverter 2
    address: 0x0421
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp Inverter 3
    address: 0x0422
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp Reserved 1
    address: 0x0423
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp Reserved 2
    address: 0x0424
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Temp Reserved 3
    address: 0x0425
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: '°C'
    skip_updates: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Generation time today
    address: 0x0426
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: 'min'
    accuracy_decimals: 0
    device_class: duration
    skip_updates: 10
    # filters:
    #   - multiply: 0.016667
    
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Generation time total
    address: 0x0427
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: 'min'
    accuracy_decimals: 0
    device_class: duration
    skip_updates: 10
    # filters:
    #   - multiply: 0.0166667
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Service time total
    address: 0x0429
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: 'min'
    accuracy_decimals: 0
    device_class: duration
    skip_updates: 10
    # filters:
    #   - multiply: 0.0166667
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Insulation resistance
    address: 0x042B
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: 'kΩ'
    accuracy_decimals: 0
    skip_updates: 10
    # filters:
    #   - multiply: 0.0166667
 
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} 0x0480
    address: 0x0480
    register_type: holding
    value_type: U_QWORD
    unit_of_measurement: ' '
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Częstotliwość
    address: 0x0484
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "Hz"
    device_class: "frequency"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
      - filter_out: 0
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Moc czynna
    id: active_power
    address: 0x0485
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "W"
    device_class: "power"
    accuracy_decimals: 0
    filters:
      - multiply: 10
    state_class: "measurement"
    on_value:
      - component.update: moc_czynna_filtrowana
 
  - platform: template
    name: ${friendly_name} Moc czynna filtrowana
    id: moc_czynna_filtrowana
    unit_of_measurement: "W"
    device_class: "power"
    lambda: |-
      return id(active_power).state;
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 5
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Moc bierna
    address: 0x0486
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "var"
    device_class: "reactive_power"
    accuracy_decimals: 0
    filters:
      - multiply: 10
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: Register_0x0487
    address: 0x0487
    register_type: holding
    value_type: S_WORD
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: Register_0x0488
    address: 0x0488
    register_type: holding
    value_type: S_WORD
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: Register_0x0489
    address: 0x0489
    register_type: holding
    value_type: S_WORD
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: Register_0x048A
    address: 0x048A
    register_type: holding
    value_type: S_WORD
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: Register_0x048B
    address: 0x048B
    register_type: holding
    value_type: S_WORD
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    id: Register_0x048C
    address: 0x048C
    register_type: holding
    value_type: S_WORD
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Output Voltage
    address: 0x048D
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: "voltage"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - filter_out: 0
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Output Current
    address: 0x048E
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "A"
    device_class: "current"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
 
 
 
##### Rejestry 0x0580 PV1 Input #####
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} 0X0580
    address: 0X0580
    register_type: holding
    value_type: U_QWORD
    unit_of_measurement: ' '
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} PV1 Napięcie
    address: 0X0584
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: "voltage"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    state_class: "measurement"
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} PV1 Natężenie
    address: 0X0585
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "A"
    device_class: "current"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    state_class: "measurement"
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} PV1 Moc
    id: pv1_power
    address: 0X0586
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "W"
    device_class: "power"
    accuracy_decimals: 0
    filters:
      - multiply: 10
    state_class: "measurement"
 
  - platform: template
    name: "${friendly_name} Sprawność PV1"
    unit_of_measurement: "%"
    state_class: 'measurement'
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |-
        return id(pv1_power).state/id(active_power).state * 100;
 
 
##### Rejestry 0x0580 PV2 Input #####
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} PV2 Napięcie
    address: 0X0587
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: "voltage"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    state_class: "measurement"
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} PV2 Natężenie
    address: 0X0588
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "A"
    device_class: "current"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    state_class: "measurement"
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} PV2 Moc
    id: pv2_power
    address: 0X0589
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "W"
    device_class: "power"
    accuracy_decimals: 0
    filters:
      - multiply: 10
    state_class: "measurement"
 
  - platform: template
    name: "${friendly_name} Sprawność PV2"
    unit_of_measurement: "%"
    state_class: 'measurement'
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |-
        return id(pv2_power).state/id(active_power).state * 100;

 
##### Rejestry 0x680 Power #####   
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} 0X0680
    address: 0X0680
    register_type: holding
    value_type: U_QWORD
    unit_of_measurement: ' '
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Energia dzisiaj
    id: inverter_energy_today
    register_type: holding
    address: 0x0684
    unit_of_measurement: "kWh"
    device_class: "energy"
    value_type: U_DWORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    state_class: "total_increasing"
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Energia całkowita
    id: inverter_energy_total
    register_type: holding
    address: 0x0686
    unit_of_measurement: "kWh"
    device_class: "energy"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    state_class: "total_increasing"
 
##### Rejestry 0x2000 Core function conf #####   
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} 0X2000
    address: 0X2000
    register_type: holding
    value_type: U_QWORD
    unit_of_measurement: ' '
    internal: true
 
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Country code
    id: country_code
    register_type: holding
    address: 0x2004
    value_type: U_WORD
 
      
# Basic switch to allow you to restart the device remotely
switch:
  - platform: restart
    name: ${friendly_name} Restart
  - platform: safe_mode
    name: ${friendly_name} Restart (Safe Mode)
 
binary_sensor:
  - platform: status
    name: ${friendly_name} Status
